title: ""
logo: /assets/images/icon.v3.svg
description: |
  https://assay.it documentation

baseurl: /
url: https://assay-it.github.io/

# theme: just-the-docs
remote_theme: fogfish/just-the-docs
color_scheme: site

search_enabled: true

aux_links:
  "Blog":
    - "/blog"
  "Community":
    - "https://assay-it.slack.com/"
  "Twitter":
    - "https://twitter.com/ItAssay"
  "GitHub":
    - "https://github.com/assay-it"

footer_content: "Copyright &copy; 2019 - 2020 <img src=/assets/images/icon.v3.svg width=19 height=19 /> Assay It "

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page"
gh_edit_repository: "https://github.com/assay-it/assay-it.github.io" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
